<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<?php
$arrContextOptions=array(
    "ssl"=>array(
        "verify_peer"=>false,
        "verify_peer_name"=>false,
    ),
);

$url = "https://portal.vietcombank.com.vn/Usercontrols/TVPortal.TyGia/pXML.aspx?b=1";
$xml = file_get_contents($url,false, stream_context_create($arrContextOptions));
$new = simplexml_load_string($xml);
$con = json_encode($new);
$data = json_decode($con, true);

?>


<style>
    .table td, .table th {
        padding: .75rem;
        vertical-align: middle;
        border-top: 1px solid #dee2e6;
        font-size: 1.75rem;
    }
    .table tbody tr:nth-of-type(odd) {
        background-color: rgba(0,0,0,.05);
    }
    .title {
        font-size: 2.75rem;
        color: #ff6347; 
        margin-bottom: 2.75rem;
        /* text-shadow: 2px 2px 4px #000000;  */
    }
</style>

<h3 class="text-center title">Vietcombank Currency Conversion Table <?= $data['DateTime'] ?></h3>
<table class="table table-hover">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Code</th>
        <th scope="col">Symbol</th>
        <th scope="col">Name</th>
        <th scope="col">Purchase Price</th>
        <th scope="col">Transfer Price</th>
        <th scope="col">Selling Price</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($data['Exrate'] as $k => $currency): ?>
        <tr>
            <th scope="row"><?= $k+1 ?></th>
            <td><?= $currency['@attributes']['CurrencyCode'] ?></td>
            <td style="font-size: 1.25rem;">
                <img src="https://flagcdn.com/h40/<?= strtolower(substr($currency['@attributes']['CurrencyCode'], 0, -1)) ?>.png">
            </td>
            <td><?= $currency['@attributes']['CurrencyName'] ?></td>
            <td><?= $currency['@attributes']['Buy'] ?></td>
            <td><?= $currency['@attributes']['Transfer'] ?></td>
            <td><?= $currency['@attributes']['Sell'] ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

