<?php
$json = @file_get_contents("https://api.rss2json.com/v1/api.json?rss_url=https://vnexpress.net/rss/kinh-doanh.rss&api_key=ggeeb0lbg20gf0sud4krunjcv88oqkxwxv5k5vym&count=30");

// Check if the API request was successful
if ($json === false) {
    die('Error fetching data from API');
}

$data = json_decode($json, true);

// Check if the data is in the expected format
if (!isset($data['items']) || !is_array($data['items'])) {
    die('Unexpected data format');
}

function getImageSrc($description) {
    preg_match('/<img[^>]+src="([^"]+)"/', $description, $match);
    $src = $match[1];
    $path = parse_url($src, PHP_URL_PATH);
    return 'https://i-kinhdoanh.vnecdn.net' . $path;
}
?>


<style>
    .card {
        width: 90%;
        margin: auto;
        margin-bottom: 40px;
        box-shadow: 0 4px 6px 0 rgba(0, 0, 0, 0.2);
        border-radius: 10px;
        overflow: hidden;
    }
    .card-container {
        display: flex;
        flex-direction: column;
        align-items: center;
    }
    .card-content {
        display: flex;
    }

    .card img {
        width: 45%;
        height: auto;
    }

    .card-body {
        font-family: Verdana, sans-serif;
        font-size: 1.5em;
        padding: 20px;
        flex-grow: 1;
        line-height: 1.4;
        margin-bottom: 10px;
    }
    .card-title {
        font-size: 1.4em;
        font-weight: bold;
        line-height: 1.4;
    }
    .card-text {
        font-family: Verdana, sans-serif;
        color: #8B4000;
    }

    .card:hover {
        transform: scale(1.1);
        transition: transform .2s;
    }

</style>


<div class="card-container">
    <?php foreach ($data['items'] as $item): ?>
        <?php $image = getImageSrc($item['description']); ?>
        <a href="<?= $item['link'] ?>" class="card-link">
            <div class="card">
                <div class="card-content">
                    <img src="<?= $image ?>" alt="Image for <?= $item['title'] ?>">
                    <div class="card-body">
                        <h4 class="card-title"><?= $item['title'] ?></h4>
                        <p class="card-text"><?= strip_tags($item['description']) ?></p>
                    </div>
                </div>
            </div>
        </a>
    <?php endforeach; ?>
</div>
