<?php
$ch = curl_init();

$url = 'https://api.openweathermap.org/data/2.5/forecast?q=Hanoi,vn&units=metric&APPID=';
$api_key = '8ab3e6d73bd00413bc0a7cecc0ac675a';
$url = $url . $api_key;

curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_URL, $url);
$result = curl_exec($ch);
curl_close($ch);

$data = json_decode($result, true);

function getIconUrl($iconName)
{
    return 'https://openweathermap.org/themes/openweathermap/assets/vendor/owm/img/widgets/' . $iconName . '.png';
}

date_default_timezone_set('Asia/Ho_Chi_Minh');

function isWithinThreeHours($datetime)
{
    $now = new DateTime();
    $datetime = new DateTime($datetime);
    $interval = $now->diff($datetime);

    // Calculate total difference in hours
    $hoursDifference = $interval->h;
    $hoursDifference += $interval->days * 24;

    // Check if datetime is within 3 hours in the past / in the future
    return $hoursDifference <= 3 || $datetime > $now;
}

function formatDateTime($datetimeString) {
    $datetime = new DateTime($datetimeString);
    return $datetime->format('H:i | d - M');
}



?>

<style>
    .title {
        font-size: 2.75rem;
        color: #ff6347; 
        margin-bottom: 2.75rem;
        font-weight: bold;
        font-family: Verdana, sans-serif;
    }

    table {
        width: 100%;
        border-collapse: collapse;
        font-family: Verdana, sans-serif;
    }

    tr:nth-child(even) {
        background-color: #FFF5EE;
    }


    .highlight-header th {
        color: #ffffff; 
        background-color: #CC5500;
    }
    .highlight-text {
        font-weight: bold;
    }

    th, td {
        border-top: 1px solid #ddd;
        text-align: center;
        vertical-align: middle;
        font-size: 1.25em;
        line-height: 1.5em;
    }
    th {
        line-height: 1.5em;
        text-align: center;
        background-color: #FFD580;
    }

    tbody tr:hover {
        color: #ffffff; 
        background-color: #f2703e;
        font-weight: bold;
    }
</style>


<?php
    $firstItem = null;
    foreach ($data['list'] as $item) {
        if (isWithinThreeHours($item['dt_txt'])) {
            $firstItem = $item;
            break;
        }
    }
?>

<?php if ($firstItem): ?>

    <h2 class="title">Current Weather</h2>
    <table>
        <thead>
            <tr class="highlight-header">
                <th>Datetime</th>
                <th>Temperature</th>
                <th>Feels Like</th>
                <th>Humidity</th>
                <th>Weather</th>
                <th>Cloudiness</th>
                <th>Wind Speed</th>
            </tr>
        </thead>

        <tbody>
            <tr class="highlight-text">
                <td><?= formatDateTime($firstItem['dt_txt']) ?></td>
                <td><?= intval($firstItem['main']['temp']) ?>°C</td>
                <td><?= intval($firstItem['main']['feels_like']) ?>°C</td>
                <td><?= $firstItem['main']['humidity'] ?>%</td>
                
                <td>
                    <img src="<?= getIconUrl($firstItem['weather'][0]['icon']) ?>" alt="<?= $firstItem['weather'][0]['description'] ?>" width="40">
                    <?= $firstItem['weather'][0]['description'] ?>
                </td>

                <td><?= $firstItem['clouds']['all'] ?>%</td>
                <td><?= $firstItem['wind']['speed'] ?> m/s</td>
            </tr>
        </tbody>
    </table>

<?php endif; ?>


<h2 class="text-center title">Upcoming Weather</h2>
<table>
    <thead>
        <tr>
            <th>Datetime</th>
            <th>Temperature</th>
            <th>Feels Like</th>
            <th>Humidity</th>
            <th>Weather</th>
            <th>Cloudiness</th>
            <th>Wind Speed</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach (array_slice($data['list'], 1) as $item): ?>
            <?php if ($item !== $firstItem && isWithinThreeHours($item['dt_txt'])): ?>
                <tr>
                    <td><?= formatDateTime($item['dt_txt']) ?></td>
                    <td><?= intval($item['main']['temp']) ?> °C</td>
                    <td><?= intval($item['main']['feels_like']) ?>°C</td>
                    <td><?= $item['main']['humidity'] ?>%</td>
                    
                    <td>
                        <img src="<?= getIconUrl($item['weather'][0]['icon']) ?>" alt="<?= $item['weather'][0]['description'] ?>" width="40">
                        <?= $item['weather'][0]['description'] ?>
                    </td>

                    <td><?= $item['clouds']['all'] ?>%</td>
                    <td><?= $item['wind']['speed'] ?> m/s</td>
                </tr>
            <?php endif; ?>
        <?php endforeach; ?>
    </tbody>
</table>
