<?php
$ch = curl_init();

$url = 'https://api.openweathermap.org/data/2.5/forecast?q=Hanoi,vn&units=metric&APPID=';
$api_key = '8ab3e6d73bd00413bc0a7cecc0ac675a';
$url = $url . $api_key;

curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_URL, $url);
$result = curl_exec($ch);
curl_close($ch);

$data = json_decode($result, true);

function getIconUrl($iconName)
{
    return 'https://openweathermap.org/themes/openweathermap/assets/vendor/owm/img/widgets/' . $iconName . '.png';
}

function isWithinThreeHours($datetime)
{
    $now = new DateTime();
    $datetime = new DateTime($datetime);
    $interval = $now->diff($datetime);
    return $interval->h <= 3 || $datetime >= $now;
}
?>

<style>
    .title {
        font-size: 2.75rem;
        color: #ff6347; 
        margin-bottom: 2.75rem;
        font-weight: bold;
        font-family: Verdana, sans-serif;
    }

    table {
        width: 100%;
        border-collapse: collapse;
        font-family: Verdana, sans-serif;
    }

    tr:nth-child(even) {
        background-color: #FFF5EE;
    }
    /* tr:hover {
        color: #FFF5EE; 
        background-color: #FBCEB1;
    } */

    .highlight-header th {
        color: #ffffff; 
        background-color: #CC5500;
    }
    .highlight-text {
        font-weight: bold;
    }

    th, td {
        border: 1px solid #ddd;
        padding: 15px;
        text-align: center;
        vertical-align: middle;
        font-size: 1.25em;
        line-height: 1.5;
    }
    th {
        background-color: #FFD580;
    }
</style>

<h2 class="title">Current Weather</h2>
<table>
    <thead>
        <tr class="highlight-header">
            <th>Date and Time</th>
            <th>Temperature</th>
            <th>Feels Like</th>
            <th>Temperature</th>
            <th>Humidity</th>
            <th>Weather</th>
            <th>Cloudiness</th>
            <th>Wind Speed</th>
        </tr>
    </thead>
    <tbody>
        <?php if (isWithinThreeHours($data['list'][0]['dt_txt'])): ?>
            <tr class="highlight-text">
                <td><?= $data['list'][0]['dt_txt'] ?></td>
                <td><?= $data['list'][0]['main']['temp'] ?>°C</td>
                <td><?= $data['list'][0]['main']['feels_like'] ?>°C</td>
                <td><?= $data['list'][0]['main']['temp_min'] ?> - <?= $data['list'][0]['main']['temp_max'] ?> °C</td>
                <td><?= $data['list'][0]['main']['humidity'] ?>%</td>
                
                <td>
                    <img src="<?= getIconUrl($data['list'][0]['weather'][0]['icon']) ?>" alt="<?= $data['list'][0]['weather'][0]['description'] ?>" width="40">
                    <?= $data['list'][0]['weather'][0]['description'] ?>
                </td>

                <td><?= $data['list'][0]['clouds']['all'] ?>%</td>
                <td><?= $data['list'][0]['wind']['speed'] ?> m/s</td>
            </tr>
        <?php endif; ?>
    </tbody>
</table>


<h2 class="text-center title">Upcoming Weather</h2>
<table>
    <thead>
        <tr>
            <th>Date and Time</th>
            <th>Temperature</th>
            <th>Feels Like</th>
            <th>Temperature</th>
            <th>Humidity</th>
            <th>Weather</th>
            <th>Cloudiness</th>
            <th>Wind Speed</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach (array_slice($data['list'], 1) as $item): ?>
            <?php if (isWithinThreeHours($item['dt_txt'])): ?>
                <tr>
                    <td><?= $item['dt_txt'] ?></td>
                    <td><?= $item['main']['temp'] ?>°C</td>
                    <td><?= $item['main']['feels_like'] ?>°C</td>
                    <td><?= $data['list'][0]['main']['temp_min'] ?> - <?= $data['list'][0]['main']['temp_max'] ?> °C</td>
                    <td><?= $item['main']['humidity'] ?>%</td>
                    
                    <td>
                        <img src="<?= getIconUrl($item['weather'][0]['icon']) ?>" alt="<?= $item['weather'][0]['description'] ?>" width="40">
                        <?= $item['weather'][0]['description'] ?>
                    </td>

                    <td><?= $item['clouds']['all'] ?>%</td>
                    <td><?= $item['wind']['speed'] ?> m/s</td>
                </tr>
            <?php endif; ?>
        <?php endforeach; ?>
    </tbody>
</table>
